version: "2"
services:
  chrome:
    image: justinribeiro/chrome-headless
    restart: on-failure
    cap_add:
      - SYS_ADMIN
    expose:
      - 9222
#    ports:
#      - "9222:9222"
    command: "google-chrome-stable --headless --disable-gpu --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222"
  app:
    image: node:8-slim
    restart: on-failure
    working_dir: /app
    user: node
    depends_on:
      - chrome
    ports:
      - 3000:3000
    environment:
      APP_ENV: ${APP_ENV}
    build:
      context: .
      args:
        app_env: ${APP_ENV}
    command: npm start